### ISSUE TITLE
Audio Track Shared Failure

### ISSUE THREAD

**Issue by alyssams** [androidthings/sample-googleassistant#17]
![screen shot 2017-05-19 at 11 52 48](https://cloud.githubusercontent.com/assets/3535711/26262627/4dbd6530-3c8a-11e7-9f3e-65a318422e40.png)

**Comment by proppy** [comment]
Does that happen after you added some code for updating volume?

Can you send a diff of the modification you made and tell us if this happens consistently?

**Comment by proppy** [comment]
Closing this as this looks specific to the [codelab](https://codelabs.developers.google.com/codelabs/androidthings-assistant/#0), feel free to re-open if you manage to reproduce this issue with the sample.
