### ISSUE TITLE
Import of ConverseConfig

### ISSUE THREAD

**Issue by alyssams** [androidthings/sample-googleassistant#18]
Add a step to import 

import com.google.assistant.embedded.v1alpha1.ConverseConfig;
and hot key for new users to Android Studio

**Comment by Fleker** [comment]
Good afternoon,
Can you state which step this line should be added to?

Thanks.

**Comment by alyssams** [comment]
hey @Fleker, this issue was found while i was at google i/o in May. I don't remember where to enhance this. sorry!

**Comment by alyssams** [comment]
unrelated question to this project but related to iot and firebase. There was a photobooth at google i/o and the dev there said it would be on github. I've searched and cannot find it. can you please help me out with this? very much appreciated!

**Comment by Fleker** [comment]
@alyssams glad to close invalid bugs :)

We are planning to post the photobooth code on GitHub. We have not done that yet. I'll make sure you're notified when that happens.

**Comment by Fleker** [comment]
@proppy close pls

**Comment by alyssams** [comment]
thank you! looking forward to checking out the photobooth code! it was super cool!

**Comment by proppy** [comment]
@Fleker added you to the repo, so you should have right to manage the issues.

**Comment by Fleker** [comment]
@alyssams we recently published the code for the photobooth!

https://github.com/androidthings/photobooth
