### ISSUE TITLE
How to get R.raw.credentials

### ISSUE THREAD

**Issue by yatindeokar** [androidthings/sample-googleassistant#19]
How to get Credentials file ;

**Comment by JonathanNakhla** [comment]
Follow these steps: https://github.com/androidthings/sample-googleassistant#run-the-sample

**Comment by proppy** [comment]
I believe @JonathanNakhla answered the question, let us know if you have any issues generate the credential resource.

**Comment by AlexKorovyansky** [comment]
Got the same confusion for a second, because `--credentials` looks as an input parameter, while it's used for output and credentials.json will be generated within `res/raw` folder by that command:

```
google-oauthlib-tool --client-secrets client_secret_NNNN.json \
                     --credentials app/src/main/res/raw/credentials.json \
                     --scope https://www.googleapis.com/auth/assistant-sdk-prototype \
                     --save
```

**Comment by proppy** [comment]
@AlexKorovyansky yep, it'd be better to rename/alias the parameter to `--save-credentials`, can you file an issue in https://github.com/GoogleCloudPlatform/google-auth-library-python-oauthlib ?

**Comment by proppy** [comment]
@AlexKorovyansky Done :)
