### ISSUE TITLE
Add support for imx7d_pico in BoardDefaults.java

### ISSUE THREAD

**Issue by JonathanNakhla** [androidthings/sample-googleassistant#20]
Mappings can be found in: https://github.com/androidthings/contrib-drivers/blob/master/rainbowhat/src/main/java/com/google/android/things/contrib/driver/rainbowhat/RainbowHat.java

**Comment by RamGude** [comment]
@JonathanNakhla Johnathan, I am not sure if @proppy and others at Google have already tested this, but I just did a test on one of our i.MX7D Pico-Pi boards and the code works. Using GPIO_34 for button. 
Cheers
