### ISSUE TITLE
Question about the steps in readme

### ISSUE THREAD

**Issue by NeilConcur** [androidthings/sample-googleassistant#21]
Hi, I found this link: https://codelabs.developers.google.com/codelabs/androidthings-assistant/index.html?index=..%2F..%2Findex#0

It has a lot more steps than what is listed in readme; however, it is meant for people who have the AIY kit.

I don't have the kit myself and am wondering if following the steps in the link plus setting AUDIO_USE_I2S_VOICEHAT_IF_AVAILABLE = false in AssistantActivity.java will work.

Please advise.

**Comment by niufen2013** [comment]
my nexus 6p has no com.google.android.things library.... what should i do? thanks

**Comment by proppy** [comment]
@NeilConcur the steps in README.md should work if you set `AUDIO_USE_I2S_VOICEHAT_IF_AVAILABLE` to `false` and use a USB microphone/speaker.


@niufen2013 this sample is meant for ["Android Things"](http://developer.android.com/things), not "Android" but you should be able to update it (remove the .things import and code) to make it work on "regular" Android.

**Comment by holachek** [comment]
Is it possible to use the 3.5mm audio output in lieu of a USB speaker? Tried to play with the settings but didn't get very far.

**Comment by proppy** [comment]
@holachek did you try to set `AUDIO_USE_I2S_VOICEHAT_IF_AVAILABLE` to `false` ?

**Comment by proppy** [comment]
@niufen2013 the current sample is only designed to run on [Android Things devices](https://developer.android.com/things/hardware/developer-kits.html).

**Comment by holachek** [comment]
@proppy For recording, I'm using a USB microphone (from Adafruit). For playback, I'm using generic headphones connected to the 3.5mm output jack. My config.txt file has PWM audio enabled (as opposed to I2S), and `AUDIO_USE_I2S_VOICEHAT_IF_AVAILABLE` is set to false. My Saleae Logic probing the 3.5mm output shows no signal output.

**Comment by CCCCoder** [comment]
@proppy  If i want to integrate google assistant on my Android phone , how to do ?

**Comment by Fleker** [comment]
@CCCCoder you should be able to use the protobufs from the gRPC module in this project (it's new!) and be able to implement the gRPC callbacks in your app.

**Comment by CCCCoder** [comment]
@Fleker Thanks for your reply .But is there any demo about that?

**Comment by Fleker** [comment]
No there is no sample code on how that could be done. However, it should not be too difficult to copy _most_ of the Android Things code and trigger the Assistant runnable on a virtual button click instead of a physical button. You won't need to use your own audio drivers either since you can use the existing AudioTrack and AudioRecord.

**Comment by CCCCoder** [comment]
@Fleker Thanks ! I think i know how to do  .

**Comment by CCCCoder** [comment]
@Fleker  Another question, how do i use this to return a intent?For example, I say like 'play music xxx', how to return intent contains music name 'xxx'?

**Comment by Fleker** [comment]
The gRPC API doesn't support any rich functionality like getting intents to certain types of activities. The best you can do is manually parse the user's query when you get a response back.

**Comment by CCCCoder** [comment]
@Fleker Thank u !!!

**Comment by proppy** [comment]
Closing this as the codelab is now live on https://codelabs.developers.google.com/codelabs/androidthings-assistant/
