### ISSUE TITLE
AndroidThings disk image might be corrupt

### ISSUE THREAD

**Issue by claucookie** [androidthings/sample-googleassistant#24]
I tried to burn the image into a sd card, an usb disk and I got always the same message saying "The disk you inserted was not readable by this computer".

Despite the message, I took the sdcard and I inserted it into the raspberry pi, with no success. It didn't boot at all and it got stuck on a rainbow screen.

I tried multiple times with preview v3.1 and v4. Alternatively, It worked with the same sdcard and the raspbian version with google assistant on it, so I Imagine there must be something wrong with the latest preview of androidThings disk image.

**Comment by tyharness** [comment]
Seems OK. dp31 and dp4 are ok for the sample assistant app.
How are you imaging the card?  Here's how to do it with Linux:

df -h
take a note of what disks are mounted.
insert sd card
df -h
hopefully you can identify the sd card and partitions.  

my card is called mmcblk0 be careful yours may be different


sudo umount /dev/mmcblk0p1  
sudo umount /dev/mmcblk0p2  
sudo umount /dev/mmcblk0p6      etc . 


make sure you're 100% sure it's the sd card before dd 

sudo dd bs=4M if=iot_rpi3.img of=/dev/mmcblk0

takes ages.

eject card and reinsert.  Does it auto mount.  If  not mount it and edit the config.txt to enable i2s. unmount and remove and put into the pi.  Use a LAN cable with internet access on first boot if you can so it'll set the date correctly.

hope it helps

**Comment by Fleker** [comment]
You could use the terminal to do imaging, but it may be useful to try using [Etcher](https://etcher.io/).

**Comment by claucookie** [comment]
Thanks for your response, in my case I was on Mac and I used Etcher several times to burn the image. So weird I guess.

**Comment by Fleker** [comment]
I recently got DP4 to run on a Pi without issue using Etcher.

" It didn't boot at all and it got stuck on a rainbow screen.”

Sounds like a Raspian component is still present on the card, potentially intefering with loading the correct OS. Are you completely wiping the card before putting data on it?

**Comment by tyharness** [comment]
When you insert the sdcard into the reader does the mac auto mount it and open some software like a file manager?  How do you unmount all the existing partitions before trying to write the image?

**Comment by proppy** [comment]
@claucookie can you share how you are flashing the image.

Note: this seems more like a "questions" for https://stackoverflow.com/questions/tagged/android-things rather than a specific bug about this sample.

**Comment by proppy** [comment]
Closing this, feel free to re-open a new issue on b.android.com if you still have issue flashing android things.
