### ISSUE TITLE
volume control

### ISSUE THREAD

**Issue by proppy** [androidthings/sample-googleassistant#3]

**Comment by JonathanNakhla** [comment]
From the looks of it, this project is purposely barebones. You can check out codelab write up which complements this project and helps you add conversation support! I've linked to the exact page: https://codelabs.developers.google.com/codelabs/androidthings-assistant/index.html?index=..%2F..%2Findex#4

**Comment by Fleker** [comment]
This feature should also support `SharedPreferences` so that the volume remains at the desired level even after a power cycle.

**Comment by Fleker** [comment]
Close pls

**Comment by proppy** [comment]
Fixed with 712ec30996b689508c3c7aacb3508e0bdb5f34c6
