### ISSUE TITLE
Need Response as text.

### ISSUE THREAD

**Issue by Ranjith1992** [androidthings/sample-googleassistant#30]
I need the response as text or json.
Any idea how to implement this case.

**Comment by Fleker** [comment]
Unfortunately this is not supported with the gRPC API right now.

**Comment by proppy** [comment]
@Ranjith1992 I encourage you to discuss this feature request with the team the http://g.co/assistantsdkdev community.

**Comment by Fleker** [comment]
We added Assistant text response in 1b1c266fdd9972b0e582f66de99eab6f050b3d18.
