### ISSUE TITLE
AudioTrack releaseBuffer warning

### ISSUE THREAD

**Issue by holachek** [androidthings/sample-googleassistant#34]
I have this app running on my Android Things Rpi3 (Dev Preview 4.1). When I click the button to record, I get a warning:
`com.example.androidthings.assistant W/AudioTrack: releaseBuffer() track 0xa71ecf00 disabled due to previous underrun, restarting`

I can't get the demo to work...Could this warning be the reason? Thanks!

**Comment by akbarxie** [comment]
could you tell me how did you solved the problem??

**Comment by holachek** [comment]
I ended up having to unplug and replug the USB audio interface. Then it worked fine. Seems like there was an error in the Linux enumeration order.
