### ISSUE TITLE
Run on Android smartphone

### ISSUE THREAD

**Issue by bluebird11** [androidthings/sample-googleassistant#35]
Hi, thanks for the great work!

I'm trying to run this on an Android smartphone and I'm getting the error:

> Installation failed with message INSTALL_FAILED_MISSING_SHARED_LIBRARY: Package couldn't be installed in /data/app/com.example.androidthings.assistant-1: Package com.example.androidthings.assistant requires unavailable shared library com.google.android.things; failing!.

Is it easily possible to modify the app to run on an Android smartphone?

**Comment by Fleker** [comment]
Take a look at the gRPC module, which just contains the protobufs. You'll need to implement a lot of the methods to interact with it, although you won't need to use any drivers.

**Comment by Ranjith1992** [comment]
I removed all dependencies of android things,Now it's working fine in android smart phone.

**Comment by bluebird11** [comment]
Wow, that sounds great! Did you make the code available somewhere?

**Comment by Ranjith1992** [comment]
@bluebird11 : Soon I will post all the steps in stackoverflow.

**Comment by bluebird11** [comment]
Great, please let us know when you do.

**Comment by Ranjith1992** [comment]
@bluebird11 : sure.

**Comment by Fleker** [comment]
We're also refactoring the Assistant integration to make it easier to move around. Should be posted this week.

**Comment by Fleker** [comment]
Commit b790b0be91b5a743fb847af6a6c95f19459162de puts everything into a single class, making it easier to integrate into other Android devices.

**Comment by sanchit97** [comment]
@Ranjith1992 Did you post the code anywhere which removes Android Things dependencies?

**Comment by sanchit97** [comment]
@Fleker Is there a version which we can directly run on Android, off-the-shelf?

**Comment by Fleker** [comment]
No we currently don't have a version that will work solely with a phone.

**Comment by YinXiuYu** [comment]
> I removed all dependencies of android things,Now it's working fine in android smart phone.

@Ranjith1992  Hi,Ranjith , I'm very glad to see you had done such tings. Can you show what steps you had done,or haven't you post the code to somewhere? Waiting for your answer very urgently!

**Comment by d3vilghost** [comment]
I have also an old smartphone runinig on android lolipop which powered by a 1.2GHz quad-core Spreadtrum SC773 cpu . Can I install android things on it
