### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by sachindroid8** [androidthings/sample-googleassistant#37]
Hi, I am facing this issue here. The old sample app used to build without any issues and I can see now the voicehat directory and gRPC directories are added. Please advice.

Error:Execution failed for task ':grpc:generateReleaseProto'.
> protoc: stdout: . stderr: /Users/Documents/DEVWorskspace/ANDROID THINGS/ANDROID THINGS PROJECTS/Google Assistant/sample-googleassistant/grpc/build/extracted-protos/main: warning: directory does not exist.
  /Users/Documents/DEVWorskspace/ANDROID THINGS/ANDROID THINGS PROJECTS/Google Assistant/sample-googleassistant/grpc/build/extracted-include-protos/main: warning: directory does not exist.
  /Users/Documents/DEVWorskspace/ANDROID THINGS/ANDROID THINGS PROJECTS/Google Assistant/sample-googleassistant/grpc/src/release/proto: warning: directory does not exist.
  /Users/Documents/DEVWorskspace/ANDROID THINGS/ANDROID THINGS PROJECTS/Google Assistant/sample-googleassistant/grpc/build/extracted-protos/release: warning: directory does not exist.
  /Users/Documents/DEVWorskspace/ANDROID THINGS/ANDROID THINGS PROJECTS/Google Assistant/sample-googleassistant/grpc/build/extracted-include-protos/release: warning: directory does not exist.
  /Users/Documents/DEVWorskspace/ANDROID THINGS/ANDROID THINGS PROJECTS/Google Assistant/sample-googleassistant/grpc/src/release/proto: warning: directory does not exist.
  /Users/Documents/DEVWorskspace/ANDROID THINGS/ANDROID THINGS PROJECTS/Google Assistant/sample-googleassistant/grpc/build/extracted-protos/release: warning: directory does not exist.
  /Users/Documents/DEVWorskspace/ANDROID THINGS/ANDROID THINGS PROJECTS/Google Assistant/sample-googleassistant/grpc/build/extracted-include-protos/release: warning: directory does not exist.
  google/api/http.proto: File not found.
  google/protobuf/descriptor.proto: File not found.
  api/annotations.proto: Import "google/api/http.proto" was not found or had errors.
  api/annotations.proto: Import "google/protobuf/descriptor.proto" was not found or had errors.
  api/annotations.proto:28:8: "google.protobuf.MethodOptions" is not defined.

**Comment by Fleker** [comment]
There was a small bug that popped up in a recent change. It will be fixed
soon.

You'll need to move the protos from sample-googleassistant
<https://github.com/androidthings/sample-googleassistant?files=1>
/grpc
<https://github.com/androidthings/sample-googleassistant/tree/master/grpc>/
src
<https://github.com/androidthings/sample-googleassistant/tree/master/grpc/src>
/main
<https://github.com/androidthings/sample-googleassistant/tree/master/grpc/src/main>
/proto to sample-googleassistant
<https://github.com/androidthings/sample-googleassistant?files=1>/grpc
<https://github.com/androidthings/sample-googleassistant/tree/master/grpc>/
src
<https://github.com/androidthings/sample-googleassistant/tree/master/grpc/src>
/main
<https://github.com/androidthings/sample-googleassistant/tree/master/grpc/src/main>
/proto/google

**Comment by Fleker** [comment]
This is fixed in commit 66a72976ae5c60894e39a75d56a8a6888cb7a3f5
