### ISSUE TITLE
follow on conversation

### ISSUE THREAD

**Issue by proppy** [androidthings/sample-googleassistant#4]

**Comment by JonathanNakhla** [comment]
From the looks of it, this project is purposely barebones. You can check out codelab write up which complements this project and helps you add conversation support! I've linked to the exact page, just scroll to the bottom a bit: https://codelabs.developers.google.com/codelabs/androidthings-assistant/index.html?index=..%2F..%2Findex#4

**Comment by Fleker** [comment]
Close pls

**Comment by proppy** [comment]
Fixed with d600303cf25343076e21729a27d15ee2420d8393
