### ISSUE TITLE
Build takes a lot of time "like a build after clean" with jackOptions

### ISSUE THREAD

**Issue by hpsaturn** [androidthings/sample-googleassistant#40]
Hi,

Ever, with each compilation the project take the same time like a build after clean. The solution take from ~4 min to 15 secs with each build. The solution is comment the next options:

```gradle
jackOptions {
            enabled true
}
```

```gradle
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
}
```
Tools:
AndroidStudio 2.3.3 stable channel. Repository same to master.

**Comment by Fleker** [comment]
I'm not sure that the issue is related to jack. When you do a build from clean you have to recreate classes from the Protobufs. That compilation process will take longer than a normal Android compilation.

**Comment by hpsaturn** [comment]
I agree, but this is the point, never it cached the binaries, all compilations have the same time. (the next compilations to first), it is a big nightmare, when disabling jack, everything goes back to normal.

**Comment by Fleker** [comment]
When I do a clean, I expect that the binaries are deleted and need to be regenerated from scratch. I have not been able to reproduce any abnormally long compilation times with a simple rebuild

**Comment by hpsaturn** [comment]
My system operative and more settings are the next:
- Debian GNU/Linux 8.9
- java version "1.8.0_144" 64-Bit
- buildToolsVersion "26.0.0" (same issues with 26.0.1)
- Gradle local properties:
    ```gradle
    org.gradle.daemon=true
    org.gradle.parallel=true
    ```
- Gradle project root properties:
    ```gradle
    org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
    ```
- VM Properties: `blank` (empty)

__________________
Source code (My fork):
[Google Assistant code for MATRIX Creator](https://github.com/hpsaturn/sample-googleassistant)

**Comment by Fleker** [comment]
Can you compile the protobufs into Java classes, then copy those classes to new files and disable the protobuf generation? I think that without that step the compilation should be faster.

**Comment by hpsaturn** [comment]
But without the jack options works fine and very fast, for this I reported this issue.

**Comment by proppy** [comment]
I think we may be able to get rid of the jack dependencies now that the `grpc` code is broken out in a separate module.

**Comment by Fleker** [comment]
It doesn't seem like we're using Jack now.
