### ISSUE TITLE
App Stuck at Title Bar

### ISSUE THREAD

**Issue by noelweichbrodt** [androidthings/sample-googleassistant#44]
App installs fine, but when started it hangs on loading. Only the title bar text is displayed on the top area and a blank rectangle for the main UI area.

`$ adb logcat *:E`
```
10-06 18:02:34.060   172  1230 E AudioFlinger: Error when setting parameters on exit: -61
10-06 18:02:37.444   316   416 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
```
No stack trace is printed in unfiltered `logcat` output.
The problem persists through multiple restarts.

**Comment by Fleker** [comment]
Which device are you running the app on?

**Comment by Fleker** [comment]
Looking at [the main layout](https://github.com/androidthings/sample-googleassistant/blob/master/app/src/main/res/layout/activity_main.xml) it seems like there won't be anything on the screen by default. I don't know if it's really "hanging" because there's nothing to expect when it starts.

**Comment by noelweichbrodt** [comment]
@Fleker pi 3, pi touchscreen. 
I was going by the Readme—the instructions following the installation step say:

>Try the assistant demo:
>  1. Press the button: recording starts.

So I was expecting a button on the main layout.

**Comment by danilobertelli** [comment]
@noelweichbrodt there's no button at main layout, the button is supposed to be plugged in the GPIO.
Or you can change the layout and add a button and call the startConversation() from EmbeddedAssistant class when clicked.

**Comment by Fleker** [comment]
Previously we were referring to a GPIO button, from the AIY Voice Kit. An on-screen button will be added to the sample soon.

**Comment by noelweichbrodt** [comment]
Ah, ok! makes sense, thanks for explaining @danilobertelli & @Fleker!
