### ISSUE TITLE
How to stop Assistant answer

### ISSUE THREAD

**Issue by danilobertelli** [androidthings/sample-googleassistant#45]
Hello guys,

I'm implementing some custom actions for my application, example, when I say "Who is your boss?", I want to do some actions.
That's the easy part.. just doing stuff at "onSpeechRecognition" based on the string.
However, I need to stop any response from Assistant.

What's the correct way to do that?
If I just call a mAudioTrack.stop() is enough? or should I change anything else?

Thanks in advance!
Danilo

**Comment by Fleker** [comment]
You may be able to stop the audio track, or you could do prevent the audio messages from being written to the audio track by changing this line:

`mAudioTrack.write(audioData, audioData.remaining(), AudioTrack.WRITE_BLOCKING);`

**Comment by danilobertelli** [comment]
Great! Thanks @Fleker !
