### ISSUE TITLE
Android Studio error run project

### ISSUE THREAD

**Issue by josuehennemann** [androidthings/sample-googleassistant#53]
When I click Run in android studio the following error occurs: Error: (143, 66) error: can not find symbol variable raw
File: sample-googleassistant-master /app/src/main/java/com/example/androidthings/assistant/AssistantActivity.java line 143.
Android Studio Version: 3.0.1.

I tried to sync the project in: Tools> Android> Sync Project with Grade Files
and then click "Run" again. But the error persists.

How to solve this?
thanks

**Comment by Fleker** [comment]
You need to follow the steps in the README to get your `credentials.json` and put it into the `res/raw/` directory.

**Comment by josuehennemann** [comment]
It worked. Thanks
