### ISSUE TITLE
Minimum SDK to run project

### ISSUE THREAD

**Issue by gnaazr95** [androidthings/sample-googleassistant#56]
What is the minimum SDK required to run this project? Would I be able to run it on a 22 or 23 SDK? Or does the project require at least a 26 minimum SDK due to library requirements.

**Comment by Fleker** [comment]
The minimum SDK version is specifically for Android Things. Much of the interaction code is dependent on the code in the developer preview for audio and peripherals. If you replace the activity code with your own (ie. removing the Android Things code), then you should be able to run it on older SDK versions.

**Comment by Fleker** [comment]
gRPC on Android seems to be supported down to API 14 according to [one of their examples](https://github.com/grpc/grpc-java/blob/master/examples/android/helloworld/app/build.gradle)

`// API level 14+ is required for TLS since Google Play Services v10.2`
