### ISSUE TITLE
Response is shown even when Google assistant has nothing to say

### ISSUE THREAD

**Issue by hskang9** [androidthings/sample-googleassistant#62]
I attended [Android Things & Actions on Google Codelab](https://developers-kr.googleblog.com/2018/02/android-things-actions-on-google-codelab.html) and found this long lines of empty response.
[video displaying the problem](https://youtu.be/GNBCnn2YOQ8)

Here is the image after #63. The response is now cleaner than before.

![nice and neat response](https://scontent-sin6-1.xx.fbcdn.net/v/t1.0-9/28378321_1802699959763605_6463218462951356267_n.jpg?oh=4b9dcd975d41dcb30e5a669d01ccc510&oe=5B19AD3B)

**Comment by Fleker** [comment]
This was fixed in 1a193036e466a2097ee09e03f2a38aa6bec9d077.
