### ISSUE TITLE
 After I opened this project, android studio reported this error

### ISSUE THREAD

**Issue by gaojuanjuan** [androidthings/sample-googleassistant#67]
Error:Could not resolve all files for configuration ':grpc:protobufToolsLocator_protoc'.
> Could not resolve com.google.protobuf:protoc:3.2.0.
  Required by:
      project :grpc
   > Could not resolve com.google.protobuf:protoc:3.2.0.
      > Could not get resource 'https://jcenter.bintray.com/com/google/protobuf/protoc/3.2.0/protoc-3.2.0.pom'.
         > Could not GET 'https://jcenter.bintray.com/com/google/protobuf/protoc/3.2.0/protoc-3.2.0.pom'. Received status code 502 from server: Bad Gateway

**Comment by Fleker** [comment]
It looks like this is a [Jcenter issue](http://status.bintray.com/) that they're currently investigating.

**Comment by gaojuanjuan** [comment]
Thank you very much, I have already solved
