### ISSUE TITLE
I cannot find the instance id of the device

### ISSUE THREAD

**Issue by gaojuanjuan** [androidthings/sample-googleassistant#69]
After registering my device，I can only find the mode id of the device without an instance id

**Comment by Fleker** [comment]
Where are you looking?

**Comment by Swirastlynn** [comment]
I look here: https://console.actions.google.com/u/0/project/<your-project-link>/deviceregistration/ which is ""Actions on Google/Device Registration" - DEVICE_MODEL_ID is here, but not a clue about DEVICE_INSTANCE_ID.  Maybe it's "Product name"? It is not obvious.

**Comment by Fleker** [comment]
You will see the model id appear in the console, although you will not see the instance id. The device instance id should be unique for every single device that you have and is not surfaced in the console. You can provide any string for testing/development and then use [the REST API](https://developers.google.com/assistant/sdk/reference/device-registration/register-device-manual) to register a new device for each device that you create in production.
