### ISSUE TITLE
I cannot find `refresh_token` in the credentials.json

### ISSUE THREAD

**Issue by Rayhahah** [androidthings/sample-googleassistant#70]
I register model in https://developers.google.cn/assistant/sdk/guides/service/python/embed/register-device#download-credentials.
Then I download the credentials.json,but I cannot find refresh_token in it

**Comment by Fleker** [comment]
You'll need to follow the [Generate Credentials](https://developers.google.cn/assistant/sdk/guides/service/python/embed/install-sample#generate_credentials) doc as well to generate the refresh token device-level credentials.

**Comment by Rayhahah** [comment]
Thank you very much
