### ISSUE TITLE
If Google Assistant Service can let the phone control the Smart home？

### ISSUE THREAD

**Issue by Rayhahah** [androidthings/sample-googleassistant#71]
I want to know that if If Google Assistant Service can let the phone like Redmi 4A to control the Third party smart home which support Google Assistant

**Comment by Rayhahah** [comment]
I can not receive deviceAction ，but I can receive the Intent

**Comment by Fleker** [comment]
I'm unfamiliar with this phone. Does it run Android? Does it not already have the Google Assistant?

**Comment by Rayhahah** [comment]
It run Android，and it have not the Google Assistant.
Can the phone which not already have the Google Assistant  control the Third party smart home ?

**Comment by Rayhahah** [comment]
How can I establish contact the Google Assistant Service and smart home devices.
For example, as I know Pixel have a setting to add smart home devices to Google Assistant

**Comment by Rayhahah** [comment]
But I really don't know, how to do on the other phone which not already have the Google Assistant

**Comment by Rayhahah** [comment]
Please tell me more detail,I really need your help.

**Comment by Fleker** [comment]
You would need to use a device with the Google Assistant settings to do the initial account link. After that, any device that uses your account (Assistant SDK device, Google Home, etc.) will be able to control your devices.

**Comment by Rayhahah** [comment]
I don't understand it too much.
I want to build the app which have the Google Assistant Service, and people can use my app to control their smart home devices （Their phone have not Google Assistant）
So, can it be possible?
Now I integrate Google Assistant Service in my app,which step should I follow ?

**Comment by Fleker** [comment]
First they'll need a phone that does have the Google Assistant to do the linking.

To integrate it in your app, you can look at this sample for how to send audio streams and playback the audio responses.

**Comment by Rayhahah** [comment]
Where can I find the Google Assistant Setting?
I can not find it in my phone (Galaxy S8+ with Android 7.0 )
How to do the linking with Google Assistant on my phone?

**Comment by Fleker** [comment]
1. Go to the Google Assistant
1. Click on the blue icon in the top-right corner. You should be in Explore.
1. Go to the overflow menu and select Settings
1. Go to Home Control. You'll see connected devices.
1. Click the **+** icon to see a list of home control providers
1. Select a provider to link the partner account to your Google account

**Comment by Rayhahah** [comment]
Can I change "Ok Google" to "Hello Birds" that awaken Google Assistant Service connection.
