### ISSUE TITLE
NXP android things starter kit screen

### ISSUE THREAD

**Issue by fghjhuang** [androidthings/sample-googleassistant#77]
when i power on the devices ,the screen of the NXP starter kit shown 2 penguins, and then show the android things start animation , so is there any way to change the display cause it is not allow to show ,when we make it into products.

**Comment by Fleker** [comment]
You can replace the Android Things logo by adding a `bootanimation.zip` in the Things console, although there currently isn't a way to replace the penguins.

**Comment by fghjhuang** [comment]
ths, you are write, i replace the logo successfully, but still can not replace the penguins
