### ISSUE TITLE
java.lang.IllegalStateException: Unknown Build.DEVICE generic_x86

### ISSUE THREAD

**Issue by CometInfosoft** [androidthings/sample-googleassistant#85]

**Comment by Fleker** [comment]
Are you trying to run this in an emulator?

**Comment by CometInfosoft** [comment]
yeah in emulator, and getting this exactly error.

Process: com.example.androidthings.assistant, PID: 31454
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.androidthings.assistant/com.example.androidthings.assistant.AssistantActivity}: java.lang.RuntimeException: Stub!

**Comment by Fleker** [comment]
This sample is designed to work on Android Things, which does not have an emulator. You'd need to make a number of changes for it to work in an emulator or on a mobile device.
