### ISSUE TITLE
HTML output does not work

### ISSUE THREAD

**Issue by AkashBang** [androidthings/sample-googleassistant#88]
Setting the HTML output checkbox true does not provide the visual response expected. onAssistantDisplayOut callback never gets called. I have checked the AssistResponse Object and the problem is the response object has a screenout_ field as null.

**Comment by Fleker** [comment]
Are you changing the device model and instance ids?

**Comment by AkashBang** [comment]
@Fleker Thanks, I had missed the step of adding the device model and instance ids, Adding them resolved the issue. 

For the folks with the same issue. 

Please register your device with the device registration tool mentioned here 

https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk

If you get an error with permission denied you would have to set the --credentials [PATH to the generated credentials.json] flag in your command and register a device
