### ISSUE TITLE
How can I get this demo to support saying that Hey Google wakes up Google assistants?

### ISSUE THREAD

**Issue by 2014james** [androidthings/sample-googleassistant#91]
How can I get this demo to support saying that Hey Google wakes up Google assistants? My project does not need any action, just wake up, talk and chat. What can I do?

**Comment by Fleker** [comment]
Hotword detection is not available in this project. You would need to implement your own hotword detection.

**Comment by Fleker** [comment]
That's different.

**Comment by 2014james** [comment]
@Fleker Hello, I want to implement the same voice functions as Google App, such as Hey Google wake-up, voice dialogue, chat and so on. What technology can I use to develop it?

**Comment by Fleker** [comment]
You would need to look at third-party hotword libraries. [Porcupine](https://github.com/Picovoice/Porcupine) is one, although I haven't used it myself.

**Comment by Fleker** [comment]
There is no such library for developers to use on Android Things provided by Google.
