### ISSUE TITLE
SKD Versinn

### ISSUE THREAD

**Issue by jssmy** [androidthings/sample-googleassistant#94]
Hi, I tried run in my android phone but this has sdk 22, in grandle I change to min 22 sdk but this has a error. How Can I make it?

manifest merger failed : uses-sdk:minsdkversion 20 cannot be smaller than version 27 declared in library [:grpc] /home/jssmy/androidstudioprojects/sample-googleassistant/grpc/build/intermediates/merged_manifests/debug/processdebugmanifest/merged/androidmanifest.xml as the library might be using apis not available in 20

**Comment by Fleker** [comment]
If you want to change the version, you'll need to update `minSdkVersion` in both the app and grpc modules. However, you'll need to be sure to make several other changes to the project to remove the dependency on Android Things.
