### ISSUE TITLE
Gradle features used in incompatible with Gradle 6

### ISSUE THREAD

**Issue by Piflyer** [androidthings/sample-googleassistant#96]
I was trying to run ` ./gradlew assembleDebug` when this keep appearing`
> Configure project :grpc
The com.google.protobuf plugin was already applied to the project: :grpc and will not be applied again after plugin: android-library

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Protobuf Gradle plugin version 0.8.6 and higher.
The following dependencies do not satisfy the required version:
root project 'sample-googleassistant-master' -> com.google.protobuf:protobuf-gradle-plugin:0.8.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
`
I tried Android studio 2.3, and the warning still persistently show. Is there a way to get rid of it. Thanks.

**Comment by Fleker** [comment]
You're using Gradle v6? Isn't the latest version v5.x?

**Comment by Fleker** [comment]
What version of the Android Studio Gradle plugin are you using?

**Comment by Piflyer** [comment]
I was able to solve this problem by downgrading the Gradle version in Project Structure. When I check back, it still keeps bugging me to update to Gradle 5.1.1, which is weird.
